name: PR tests check

on:
  pull_request:
    branches-ignore:
      - master
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Set up golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Run all tests
        run: go test -v ./...